### ISSUE TITLE
Switch to GLIB

### ISSUE THREAD

**Issue by YPares** [stephenpascoe/hs-arrow#1]
Hi @stephenpascoe ,
I'm interesting in this binding, and I was just wondering why you chose to make the switch from depending on the C++ API to depending on the GLIB port, and also on what is the state of the bindings?
(I only slightly used arrow in Python, I haven't been exposed to its internal APIs, so my question might feel candid)

**Comment by stephenpascoe** [comment]
Hi @YPares,
This is just an experimental side project.  I'm inexperienced with Haskell and was looking for a something practical to help me learn it.  I may progress this in future but it is currently not being worked on.

I had difficulty getting a binding on top of C++ API to work because pyarrow-C++ uses modern C++ features (particularly Enums).  This might be because of my inexperience in Haskell bindings.  IIRC I was trying to use inline-c-cpp (http://hackage.haskell.org/package/inline-c-cpp)

If you can get something to work I would happily abandon the GLIB route and could contribute to another binding.  My ambition was to start flashing out the Haskell-level API and maybe try to replace the binding layer with direct C++ API in the future.
